// Code generated by coz. DO NOT EDIT.
/**
 * Geo location utility
 * @module the-geo
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const TheGeo_ = require('./TheGeo')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheGeo = _d(TheGeo_)
exports.create = _d(create_)

module.exports = _d(default__)
